// 格式如下
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const GET_EXCHANGE_RATE = 'GET_EXCHANGE_RATE';
export const GET_CURRENCY_LIST = 'GET_CURRENCY_LIST';
export const GET_ORGANIZATION_CURRENCY = 'GET_ORGANIZATION_CURRENCY';
export const INITIAL_CURRENCY = 'INITIAL_CURRENCY';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const UPDATE_LIST = 'UPDATE_LIST';
export const PAGE_NUMBER = 'PAGE_NUMBER';
export const SELECT_POST = 'SELECT_POST';